In [ ]:
modules-->predefined packages,userdefined
pre-defined-math,os,random,string,statistics
user-defined-
module 
we used user-defined module
diff ways of importing modules
1.import modulename
2.import module as alias_name
from module import ....
from module import *



In [2]:
numpy package:
    numerical data
    computation on numerics
#diff bw numpy array and python list
1.less memory
2.fast
3.convinient

In [6]:
import numpy as np

In [7]:
#1-d array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(a.ndim)
a1.ndim

1


2

In [10]:
a1.shape

(3, 3)

In [11]:
a.shape

(5,)

In [13]:
print(a1.shape[0])#rows
print(a1.shape[1])#columns

3
3


In [16]:
#insert ele into array dynamically
a3 = np.array([],dtype="int64")
a3=np.append(a3,int(input()))
a3.dtype

12


dtype('int64')

In [17]:
a3=np.append(a3,[2,3,4,5])
a3

array([12,  2,  3,  4,  5], dtype=int64)

In [19]:
a1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#slicing
print(a3[3])

4


In [21]:
print(a1[1,1])

5


In [23]:
print(a1[2:,:])

[[7 8 9]]


In [24]:
print(a1[2:,0:2])

[[7 8]]


In [26]:
print(a1[0,0:2])

[1 2]


In [28]:
print(a1[0::2,:])


[[1 2 3]
 [7 8 9]]


In [30]:
for row in a1:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [32]:
for ele in a1.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 

In [34]:
np.array(a1.flat)#v can get 1d array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
###indexing with boolean array
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [42]:
result=(arr1 %2==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [43]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
#appending array
ar1=np.arange(1,10).reshape(3,3)
ar2=np.arange(11,20).reshape(3,3)
print(ar1)
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [47]:
print(np.vstack((ar1,ar2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [48]:
print(np.hstack((ar1,ar2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [ ]:
#attributes in mumpy
1.size
2.itemsize
3.dtype
4.ndim
5.shape

In [50]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


In [52]:
#functions 
#1.zeros
z=np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
o=np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [56]:
f=np.full((2,2),"priya")
f

array([['priya', 'priya'],
       ['priya', 'priya']], dtype='<U5')

In [58]:
e=np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [61]:
#linspace()-->linear spacing elements
l=np.linspace(1,10,5,dtype="int32")#staring ending how many parts to be divided
l

array([ 1,  3,  5,  7, 10])

In [62]:
r=np.ravel(e)#ravel sme as flat
r

array([1, 0, 0, 0, 1, 0, 0, 0, 1])

In [63]:
#function:
print(a.min())
print(a.max())
print(a.sum())

1
5
15


In [65]:
print(ar1.sum(axis=1))#sum of row ele

[ 6 15 24]


In [66]:
print(ar1.sum(axis=0))#sum of col ele

[12 15 18]


In [72]:
np.sqrt(a)
np.mean(a)
np.median(a)
np.std(a)

1.4142135623730951

In [74]:
#mathemtical operations
print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)
print(ar1/ar2)
print(ar1%ar2)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
#dot()-->matrix multiplication-->
#arr1=mxn
#arr2=nx1
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)


array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [77]:
#transpose
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
#APPLY USER DEFINED FUNCTIONS:
l1=list(range(1,20))
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [80]:
#1/(1+1)--->x/(x+1)
result=[x/(x+1) for x in l1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [81]:
a=np.array(l1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [82]:
#same operation on numpy
f=np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [83]:
import math

[str(round(math.pi)) for i in range (1, 6)]

['3', '3', '3', '3', '3']

In [84]:
C = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']

s = []

for i in range(3):

    s.append(C[i::3])

print(s)

[['a', 'd', 'g', 'j', 'm'], ['b', 'e', 'h', 'k', 'n'], ['c', 'f', 'i', 'l']]


In [85]:
def loop(start, stop, step):

    return_string = ""

    if step == 0:

        step = 1 or -1

    elif start>stop:

        step = abs(step) * -1

    for count in range(start, stop, step):

        return_string += str(count) + " "

    return return_string.strip()

print(loop(11,2,3))




11 8 5


In [86]:
import random
random.random()

0.02949240166847611

In [87]:
f = None


for i in range (5):

    with open("myfile.txt", "w") as f:

        if i > 2:

            break


print (f.closed)

True
