In [13]:
from numpy import random
print(random.randint(1,100))
print(random.rand())#float number bw 0-1

30
0.5655653368368707


In [4]:
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))
print(random.randint(100,size=(3)))

[[ 1 34 64 81]
 [18 22 57  4]
 [36 78 28 88]]
[[[55 93]
  [94  8]
  [61 13]
  [62 67]]

 [[73 20]
  [57 31]
  [56 14]
  [47 93]]

 [[83 54]
  [51 96]
  [41 20]
  [80 89]]]
[72 50 49]


In [6]:
print(random.rand(2,3))
print(random.rand(3))

[[0.46983011 0.96993759 0.44618543]
 [0.57062277 0.00300459 0.86786263]]
[0.47061939 0.7026167  0.40520133]


In [15]:
a=random.randint(100,size=(3,2)).ravel()
a

array([92, 12, 35, 61,  6, 63])

In [18]:
random.choice(a)

6

In [19]:
random.choice([1,2,3,4,5],size=(4,4))

array([[1, 1, 5, 3],
       [1, 3, 4, 2],
       [1, 5, 4, 4],
       [1, 2, 4, 2]])

In [ ]:
#panda package----------------->
1.data manipulation(large set of data-->changes)
analysis and cleaning
2.types of data
tabular data,unlabelled data(without headings or row names)
extract data v should make as data frames
dataframes--->rows and coloumns
the part of dataframe called as series in the frames

In [ ]:
#creating a dataframes
1.using 2 dictionaries

In [2]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':2,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}   
data={"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df 

First  Second
a      1       5
b      2       6
c      2       7
d      4       8
e      5       9

In [3]:
2.#simple dictionary--->dataframe
d1={"name":["preeti","priya","anitha"],"address":["hyd","adb","Ap"]}
df1=pd.DataFrame(d1)
df1

name address
0  preeti     hyd
1   priya     adb
2  anitha      Ap

In [4]:
#using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([1.2,7.2,3.9,4.6,5.9,6.9,7.5,8.3,9.5,10.1])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"colum1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

colum1  column2 column3
0       1      1.2       a
1       2      7.2       b
2       3      3.9       c
3       4      4.6       d
4       5      5.9       e
5       6      6.9       f
6       7      7.5       g
7       8      8.3       h
8       9      9.5       i
9      10     10.1       j

In [5]:
#selecting data from dataframe:
df3["column2"]

0     1.2
1     7.2
2     3.9
3     4.6
4     5.9
5     6.9
6     7.5
7     8.3
8     9.5
9    10.1
Name: column2, dtype: float64

In [6]:
df3[["column2","column3"]]

column2 column3
0      1.2       a
1      7.2       b
2      3.9       c
3      4.6       d
4      5.9       e
5      6.9       f
6      7.5       g
7      8.3       h
8      9.5       i
9     10.1       j

In [ ]:
#selecting data from the dataframe
1.loc
2.iloc

In [8]:
#single column
df3.loc[:,"colum1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: colum1, dtype: int64

In [9]:
df3.loc[:,["colum1","column2"]]

colum1  column2
0       1      1.2
1       2      7.2
2       3      3.9
3       4      4.6
4       5      5.9
5       6      6.9
6       7      7.5
7       8      8.3
8       9      9.5
9      10     10.1

In [10]:
df3.loc[0:5,["colum1","column2"]]

colum1  column2
0       1      1.2
1       2      7.2
2       3      3.9
3       4      4.6
4       5      5.9
5       6      6.9

In [11]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: colum1, dtype: int64

In [12]:
df3.iloc[0:4,0:1]

colum1
0       1
1       2
2       3
3       4

In [14]:
#retrieving the information of dataframe
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   colum1   10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [15]:
df3.shape

(10, 3)

In [16]:
df3.columns

Index(['colum1', 'column2', 'column3'], dtype='object')

In [17]:
df3.index

RangeIndex(start=0, stop=10, step=1)

In [19]:
#viewing data from dataframe:
#1.head()
#2.tail()
#3.sample()

In [20]:
df3.head()#1st 5 rows 

colum1  column2 column3
0       1      1.2       a
1       2      7.2       b
2       3      3.9       c
3       4      4.6       d
4       5      5.9       e

In [21]:
df3.head(3)

colum1  column2 column3
0       1      1.2       a
1       2      7.2       b
2       3      3.9       c

In [22]:
df3.tail()

colum1  column2 column3
5       6      6.9       f
6       7      7.5       g
7       8      8.3       h
8       9      9.5       i
9      10     10.1       j

In [23]:
df3.tail(3)

colum1  column2 column3
7       8      8.3       h
8       9      9.5       i
9      10     10.1       j

In [25]:
df3.sample()#random any row

colum1  column2 column3
9      10     10.1       j

In [26]:
df3.sample(2)#random any 2 rows

colum1  column2 column3
6       7      7.5       g
4       5      5.9       e

In [28]:
df3.describe()

colum1    column2
count  10.00000  10.000000
mean    5.50000   6.510000
std     3.02765   2.701214
min     1.00000   1.200000
25%     3.25000   4.925000
50%     5.50000   7.050000
75%     7.75000   8.100000
max    10.00000  10.100000

In [35]:
#change column headers
df3.rename(columns={"colum1":"First","column2":"Second","column3":"Third"})


AttributeError: 'NoneType' object has no attribute 'rename'

In [36]:
arr1 = np.arange(9).reshape(3,3)

arr1[:,[1,2]] = arr1[:,[2,1]]

print(arr1)



[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [37]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])

c=np.append(a,b,axis=1)

print(c)



[[ 1  2  3 11 21 31]
 [ 4  5  6 42 52 62]
 [ 7  8  9 73 83 93]]


In [40]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

print(np.concatenate([a, b], axis=0))
print(np.vstack([a, b]))
print(np.r_[a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [41]:
rand_arr = np.random.randint(1,15,4) 
print(rand_arr)

[ 3 12  5 12]


In [42]:
rand_arr = int(np.random.rand(1,15,4)) 
print(rand_arr)


TypeError: only size-1 arrays can be converted to Python scalars